config/routes.rb
Webfs::Application.routes.draw do
  resources :books

  resources :blobs

  resources :inodes do
    member do
      get 'open'
    end
  end
  
  get "/fs/ls",   to: FsController.action(:ls),   as: :fs_ls
  get "/fs/open", to: FsController.action(:open), as: :fs_open
  get "/fs/download", to: FsController.action(:download), as: :fs_download
    

  

end

app/models/inode.rb
class Inode < ActiveRecord::Base
=begin
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  mapping do
    indexes :id,            :index    => :not_analyzed
    indexes :shasum,        :analyzer => :not_analyzed
    indexes :content_type,  :analyzer => 'snowball'
    indexes :content_size,  :as       => 'content.size'
    indexes :author,        :analyzer => 'keyword'
    indexes :published_on,  :type => 'date', :include_in_all => false
  end
  
  def content
    File.read(self.uri)
  end  
=end
  
end

app/controllers/inodes_controller.rb
class InodesController < ApplicationController
  before_action :set_inode, only: [:show, :edit, :update, :destroy]
  
  helper_method :sort_column, :sort_direction

  # GET /inodes
  # GET /inodes.json
  def index
    @inodes = Inode.order(sort_column + " " + sort_direction).page params[:page]
  end

  # GET /inodes/1
  # GET /inodes/1.json
  def show
  end

  # GET /inodes/new
  def new
    @inode = Inode.new
  end

  # GET /inodes/1/edit
  def edit
  end
  
  def open
    inode = Inode.find(params[:id])
    app = "Preview"
    if inode.content_type =~ /^text\/.+$/
      app = "TextMate"
    end
    system "open -a #{app} #{inode.uri}"
    redirect_to request.referer
  end

=begin  
  def preview  
    inode = Inode.find(params[:id])  
    response.headers['Cache-Control'] = "public, max-age=#{12.hours.to_i}"
    response.headers['Content-Type'] = inode.content_type
    response.headers['Content-Disposition'] = 'inline'
    render text: File.read(inode.uri), content_type: content_type
  end
=end

  # POST /inodes
  # POST /inodes.json
  def create
    @inode = Inode.new(inode_params)

    respond_to do |format|
      if @inode.save
        format.html { redirect_to @inode, notice: 'Inode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inode }
      else
        format.html { render action: 'new' }
        format.json { render json: @inode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inodes/1
  # PATCH/PUT /inodes/1.json
  def update
    respond_to do |format|
      if @inode.update(inode_params)
        format.html { redirect_to @inode, notice: 'Inode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inodes/1
  # DELETE /inodes/1.json
  def destroy
    @inode.destroy
    respond_to do |format|
      format.html { redirect_to inodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inode
      @inode = Inode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inode_params
      params.require(:inode).permit(:shasum, :uri, :size, :content_type, :name)
    end

    def sort_column
      Inode.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/inodes_helper.rb
module InodesHelper
end

app/views/inodes/_form.html.erb
<%= form_for(@inode) do |f| %>
  <% if @inode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inode.errors.count, "error") %> prohibited this inode from being saved:</h2>

      <ul>
      <% @inode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shasum %><br>
    <%= f.text_field :shasum %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inodes/edit.html.erb
<h1>Editing inode</h1>

<%= render 'form' %>

<%= link_to 'Show', @inode %> |
<%= link_to 'Back', inodes_path %>

app/views/inodes/index.html.erb
<h1>Listing inodes</h1>
<table class="table table-bordered">
  <thead>
    <tr>			
      <th><%=raw sortable "name" %></th>
      <th><%=raw sortable "size" %></th>
      <th><%=raw sortable "content_type" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @inodes.each do |inode| %>
      <tr data-shasum="<%= inode.shasum %>">				
        <td><%= content_tag :a, inode.name, data: {toggle: "modal", target:"#previewModal", id: inode.id, uri: inode.uri, mime: inode.content_type, title: inode.name, link: preview_path(:inodes, inode.id)} %></td>
        <td><%= number_to_human_size(inode.size) %></td>
        <td><%= inode.content_type %></td>
        <td><%= link_to 'Edit', edit_inode_path(inode) %></td>
        <td><%= link_to 'Destroy', inode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @inodes %>

<br>

<%= link_to 'New Inode', new_inode_path %>

app/views/inodes/new.html.erb
<h1>New inode</h1>

<%= render 'form' %>

<%= link_to 'Back', inodes_path %>

app/views/inodes/open.html.erb
Open File Success.

app/views/inodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shasum:</strong>
  <%= @inode.shasum %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @inode.uri %>
</p>

<p>
  <strong>Size:</strong>
  <%= @inode.size %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @inode.content_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @inode.name %>
</p>

<%= preview(@inode) %>

<%= link_to 'Edit', edit_inode_path(@inode) %> |
<%= link_to 'Back', inodes_path %>