config/routes.rb
Webfs::Application.routes.draw do
  resources :books

  resources :blobs

  resources :inodes do
    member do
      get 'open'
    end
  end
  
  get "/fs/ls",   to: FsController.action(:ls),   as: :fs_ls
  get "/fs/open", to: FsController.action(:open), as: :fs_open
  get "/fs/download", to: FsController.action(:download), as: :fs_download
    

  

end

app/models/blob.rb
class Blob < ActiveRecord::Base
end

app/controllers/blobs_controller.rb
class BlobsController < ApplicationController
  before_action :set_blob, only: [:show, :edit, :update, :destroy]

  # GET /blobs
  # GET /blobs.json
  def index
    @blobs = Blob.page params[:page]
  end

  # GET /blobs/1
  # GET /blobs/1.json
  def show
  end

  # GET /blobs/new
  def new
    @blob = Blob.new
  end

  # GET /blobs/1/edit
  def edit
  end

  # POST /blobs
  # POST /blobs.json
  def create
    @blob = Blob.new(blob_params)

    respond_to do |format|
      if @blob.save
        format.html { redirect_to @blob, notice: 'Blob was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blob }
      else
        format.html { render action: 'new' }
        format.json { render json: @blob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blobs/1
  # PATCH/PUT /blobs/1.json
  def update
    respond_to do |format|
      if @blob.update(blob_params)
        format.html { redirect_to @blob, notice: 'Blob was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blobs/1
  # DELETE /blobs/1.json
  def destroy
    @blob.destroy
    respond_to do |format|
      format.html { redirect_to blobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blob
      @blob = Blob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blob_params
      params.require(:blob).permit(:digest, :uri, :size, :content_type, :name)
    end
end

app/helpers/blobs_helper.rb
module BlobsHelper
end

app/views/blobs/_form.html.erb
<%= form_for(@blob) do |f| %>
  <% if @blob.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blob.errors.count, "error") %> prohibited this blob from being saved:</h2>

      <ul>
      <% @blob.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :digest %><br>
    <%= f.text_field :digest %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blobs/edit.html.erb
<h1>Editing blob</h1>

<%= render 'form' %>

<%= link_to 'Show', @blob %> |
<%= link_to 'Back', blobs_path %>

app/views/blobs/index.html.erb
<h1>Listing blobs</h1>

<table>
  <thead>
    <tr>
      <th>Digest</th>
      <th>Name</th>
      <th>Size</th>
      <th>Content type</th>
      <th>创建时间</th>
      <th>更新时间</th>
<!-- 
      <th></th>
      <th></th>
      <th></th>
-->
    </tr>
  </thead>

  <tbody>
    <% @blobs.each do |blob| %>
      <tr>	
				<td><%= blob.digest %></td>
        <td style="width:200px;" data-uri="<%= blob.uri %>"><%= blob.name %></td>
        <td><%= blob.size %></td>
        <td><%= blob.content_type %></td>
				<td><%= blob.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= blob.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
<!-- 
        <td><%= link_to 'Show', blob %></td>
        <td><%= link_to 'Edit', edit_blob_path(blob) %></td>
        <td><%= link_to 'Destroy', blob, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
		<%= paginate @blobs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blob', new_blob_path %>

app/views/blobs/new.html.erb
<h1>New blob</h1>

<%= render 'form' %>

<%= link_to 'Back', blobs_path %>

app/views/blobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Digest:</strong>
  <%= @blob.digest %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @blob.uri %>
</p>

<p>
  <strong>Size:</strong>
  <%= @blob.size %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @blob.content_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @blob.name %>
</p>

<%= link_to 'Edit', edit_blob_path(@blob) %> |
<%= link_to 'Back', blobs_path %>